from __future__ import annotations

"""
A camada "domain" serve para centralizar as regras de negócio centrais do sistema, separando o núcleo das regras (entidades, lógica, invariantes) da infraestrutura e da aplicação/orquestração. 
É o "coração" do sistema, onde se define "o que" o sistema faz, suas entidades, valores e políticas, de maneira isolada de padrões de implementação ou detalhes de frameworks, bancos e UI. 
Dessa forma, o domínio permanece estável, fácil de testar, evoluir e reutilizar.

O subdiretório "ports" representa "portas de entrada/saída" para o domínio — interfaces (ou Protocols) que descrevem como o mundo externo pode interagir com o núcleo de regras de negócio. 
Os "ports" existem para garantir que o domínio dependa apenas de interfaces abstratas, e nunca da implementação concreta de repositórios, APIs, serviços, etc. Assim, invertem-se as dependências: 
- O domínio define o contrato (por exemplo, um método salvar(), buscar(), etc), 
- a infraestrutura implementa esse contrato em classes reais.

Essa separação facilita a troca de infraestrutura sem impactar o núcleo, permite mocks e stubs para testes e mantém o domínio desacoplado de detalhes externos.
"""

from typing import Any, Dict, List, Protocol


class ConsolidacaoRepository(Protocol):
    def listar_periodos(self) -> List[Dict[str, Any]]: ...
    def criar_periodo_consolidacao(self, periodo: str, obs: str = "") -> int: ...
    def apagar_periodo(self, periodo: str): ...
    def buscar_consolidacao(self, periodo: str) -> Dict[str, Any] | None: ...
    def atualizar_cgr(self, periodo: str, valor: float): ...
    def atualizar_cgf(self, periodo: str, valor: float): ...
    def atualizar_ret(self, periodo: str, valor: float): ...
    def atualizar_rp(self, periodo: str, valor: float): ...
    def atualizar_campos_consolidacao(self, periodo: str, **campos: float): ...
    def salvar_rpv(self, periodo: str, rpv: float): ...
    def salvar_scg(self, periodo: str, scg: float): ...
    def fechar(self): ...


class PMPVRepository(Protocol):
    def criar_sessao(self, nome: str, observacoes: str = "") -> int: ...
    def salvar_dados_mes(self, sessao_id: int, mes: int, dados: List[Dict[str, Any]]) -> bool: ...
    def salvar_resultado(
        self,
        sessao_id: int,
        vol_tot: float,
        vp_tot: float,
        vf_tot: float,
        custo_tot: float,
        pmpv: float,
        cg: float,
        final: float,
    ) -> bool: ...
    def salvar_pmpv_mensal(self, periodo: str, pmpv: float): ...
    def listar_periodos(self) -> List[Dict[str, Any]]: ...
    def listar_pmpv_mensal(self) -> List[Dict[str, Any]]: ...
    def buscar_pmpv_mensal(self, periodo: str) -> float | None: ...
    def fechar(self): ...


class SRRepository(Protocol):
    """Porta de saída para o módulo SR (Saldo Regulatório).

    Cobre tanto a sessão simples VP/VF (histórico) quanto o SR trimestral
    (VP/VF/PR/SELIC/SR-anterior por mês, ver Src/Views/tela_sr.py).
    """
    def listar_sessoes_com_volumes(self) -> List[Dict[str, Any]]: ...
    def carregar_dados_mes(self, sessao_id: int, mes: int) -> List[Dict[str, Any]]: ...
    def buscar_cgf_resumo(self, periodo: str) -> Dict[str, Any] | None: ...
    def salvar_sr(self, periodo: str, vp: float, vf: float, pr: float, sr: float): ...
    def buscar_sr(self, periodo: str) -> Dict[str, Any] | None: ...
    def salvar_sr_trimestre(self, trimestre: str, meses: List[Dict[str, Any]]): ...
    def buscar_sr_trimestre(self, trimestre: str) -> List[Dict[str, Any]]: ...
    def listar_sr_trimestres(self) -> List[str]: ...
    def fechar(self): ...


class PRRepository(Protocol):
    """Porta de saída para os resultados finais PR e PV.

    Agrupa o acesso às tabelas de resultado final (pr_resultados, pv_resultados)
    e às leituras de SR/PMPV de que esses cálculos dependem.
    """
    # PR
    def listar_sr(self) -> List[Dict[str, Any]]: ...
    def buscar_sr(self, periodo: str) -> Dict[str, Any] | None: ...
    def buscar_pr(self, periodo: str) -> Dict[str, Any] | None: ...
    def salvar_pr(self, periodo: str, scg: float, sr: float, vp: float, pr: float): ...
    def listar_pr(self) -> List[Dict[str, Any]]: ...
    # PV (depende de PMPV e PR)
    def buscar_pmpv_mensal(self, periodo: str) -> float | None: ...
    def buscar_pv(self, periodo: str) -> Dict[str, Any] | None: ...
    def salvar_pv(self, periodo: str, pmpv: float, pr: float, pv: float): ...
    def listar_pv(self) -> List[Dict[str, Any]]: ...
    def fechar(self): ...