from __future__ import annotations

from typing import Any, Dict, List, Protocol


class ConsolidacaoRepository(Protocol):
    def listar_periodos(self) -> List[Dict[str, Any]]: ...
    def criar_periodo_consolidacao(self, periodo: str, obs: str = "") -> int: ...
    def apagar_periodo(self, periodo: str): ...
    def buscar_consolidacao(self, periodo: str) -> Dict[str, Any] | None: ...
    def atualizar_cgr(self, periodo: str, valor: float): ...
    def atualizar_cgf(self, periodo: str, valor: float): ...
    def atualizar_ret(self, periodo: str, valor: float): ...
    def atualizar_rp(self, periodo: str, valor: float): ...
    def atualizar_campos_consolidacao(self, periodo: str, **campos: float): ...
    def salvar_rpv(self, periodo: str, rpv: float): ...
    def salvar_scg(self, periodo: str, scg: float): ...
    def fechar(self): ...


class PMPVRepository(Protocol):
    def criar_sessao(self, nome: str, observacoes: str = "") -> int: ...
    def salvar_dados_mes(self, sessao_id: int, mes: int, dados: List[Dict[str, Any]]) -> bool: ...
    def salvar_resultado(
        self,
        sessao_id: int,
        vol_tot: float,
        custo_tot: float,
        pmpv: float,
        cg: float,
        final: float,
    ) -> bool: ...
    def salvar_pmpv_mensal(self, periodo: str, pmpv: float): ...
    def listar_periodos(self) -> List[Dict[str, Any]]: ...
    def listar_pmpv_mensal(self) -> List[Dict[str, Any]]: ...
    def buscar_pmpv_mensal(self, periodo: str) -> float | None: ...
    def fechar(self): ...
